#ifndef TA_MEDIA_CRYPTO_H
#define TA_MEDIA_CRYPTO_H

#define TA_MEDIA_CRYPTO_UUID { \
    0x8aaaf200, 0x2450, 0x11e4, \
    { 0xab, 0xe2, 0x00, 0x02, 0xa5, 0xd5, 0xc5, 0x1b } \
}

#define TA_MEDIA_CRYPTO_KEY_SIZE      16
#define TA_MEDIA_CRYPTO_IV_SIZE       16
#define TA_MEDIA_CRYPTO_HMAC_KEY_SIZE 64
#define TA_MEDIA_CRYPTO_HMAC_SIZE     32

#define TA_MEDIA_CRYPTO_CMD_INC_VALUE    0
#define TA_MEDIA_CRYPTO_CMD_ENCRYPT_INIT 1
#define TA_MEDIA_CRYPTO_CMD_DECRYPT_INIT 2
#define TA_MEDIA_CRYPTO_CMD_UPDATE       3
#define TA_MEDIA_CRYPTO_CMD_FINISH       4
#define TA_MEDIA_CRYPTO_CMD_HMAC_INIT    5
#define TA_MEDIA_CRYPTO_CMD_HMAC_UPDATE  6
#define TA_MEDIA_CRYPTO_CMD_HMAC_FINAL   7
#define TA_MEDIA_CRYPTO_CMD_HMAC_FINISH  8

#endif /* TA_MEDIA_CRYPTO_H */
